"""add tables4

Revision ID: aa8fd50c6259
Revises: ae81f3ba7173
Create Date: 2023-08-12 20:43:57.732684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8fd50c6259'
down_revision: Union[str, None] = 'ae81f3ba7173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dic_program_lang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_program_lang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('program_lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['program_lang_id'], ['dic_program_lang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_program_lang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('program_lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_lang_id'], ['dic_program_lang.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_program_lang')
    op.drop_table('portfolio_program_lang')
    op.drop_table('dic_program_lang')
    # ### end Alembic commands ###
